# ignore_for_file: asset_directory_does_not_exist

name: wolof_bible
description: Wolof Bible app for desktop and web from USFM files.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+14

environment:
  sdk: ">=3.3.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.2
  system_theme: ^3.1.2
  window_manager: ^0.5.1
  flutter_acrylic: ^1.0.0+2
  url_strategy: ^0.3.0
  url_launcher: ^6.1.9
  share_plus: ^12.0.0
  clipboard: ^2.0.2
  fluent_ui: ^4.13.0
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  xml: ^6.1.0
  # just_audio: ^0.9.24
  # audio_session: ^0.1.6+1
  firebase_core: ^4.1.1
  firebase_analytics: ^12.0.2
  scrollable_positioned_list: ^0.3.2
  google_fonts: ^6.0.0

  flutter_html: ^3.0.0-alpha.6
  context_menus: ^2.0.0+1
  flutter_native_splash: ^2.3.7
  diacritic: ^0.1.3
  universal_html: ^2.0.8
  pwa_install: ^0.0.5
  package_info_plus: ^9.0.0
  path_provider: ^2.1.1
  snowball_stemmer: ^0.1.0
  skeletonizer: ^2.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.1.11
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  msix: ^3.7.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_ios: "assets/images/app-logo-apple.png"
  remove_alpha_ios: true
  image_path: "assets/images/app-logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/app-logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/app-logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/app-logo-apple.png"

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/
    - assets/json/C01/1CH/
    - assets/json/C01/1CO/
    - assets/json/C01/1JN/
    - assets/json/C01/1KI/
    - assets/json/C01/1PE/
    - assets/json/C01/1SA/
    - assets/json/C01/1TH/
    - assets/json/C01/1TI/
    - assets/json/C01/2CH/
    - assets/json/C01/2CO/
    - assets/json/C01/2JN/
    - assets/json/C01/2KI/
    - assets/json/C01/2PE/
    - assets/json/C01/2SA/
    - assets/json/C01/2TH/
    - assets/json/C01/2TI/
    - assets/json/C01/3JN/
    - assets/json/C01/ACT/
    - assets/json/C01/AMO/
    - assets/json/C01/COL/
    - assets/json/C01/DAN/
    - assets/json/C01/DEU/
    - assets/json/C01/ECC/
    - assets/json/C01/EPH/
    - assets/json/C01/EST/
    - assets/json/C01/EXO/
    - assets/json/C01/EZK/
    - assets/json/C01/EZR/
    - assets/json/C01/GAL/
    - assets/json/C01/GEN/
    - assets/json/C01/HAB/
    - assets/json/C01/HAG/
    - assets/json/C01/HEB/
    - assets/json/C01/HOS/
    - assets/json/C01/ISA/
    - assets/json/C01/JAS/
    - assets/json/C01/JDG/
    - assets/json/C01/JER/
    - assets/json/C01/JHN/
    - assets/json/C01/JOB/
    - assets/json/C01/JOL/
    - assets/json/C01/JON/
    - assets/json/C01/JOS/
    - assets/json/C01/JUD/
    - assets/json/C01/LAM/
    - assets/json/C01/LEV/
    - assets/json/C01/LUK/
    - assets/json/C01/MAL/
    - assets/json/C01/MAT/
    - assets/json/C01/MIC/
    - assets/json/C01/MRK/
    - assets/json/C01/NAM/
    - assets/json/C01/NEH/
    - assets/json/C01/NUM/
    - assets/json/C01/OBA/
    - assets/json/C01/PHM/
    - assets/json/C01/PHP/
    - assets/json/C01/PRO/
    - assets/json/C01/PSA/
    - assets/json/C01/REV/
    - assets/json/C01/ROM/
    - assets/json/C01/RUT/
    - assets/json/C01/SNG/
    - assets/json/C01/TIT/
    - assets/json/C01/ZEC/
    - assets/json/C01/ZEP/
    - assets/json/C01/index/
    - assets/json/C02/1CO/
    - assets/json/C02/1JN/
    - assets/json/C02/1PE/
    - assets/json/C02/1TH/
    - assets/json/C02/1TI/
    - assets/json/C02/2CO/
    - assets/json/C02/2JN/
    - assets/json/C02/2PE/
    - assets/json/C02/2TH/
    - assets/json/C02/2TI/
    - assets/json/C02/3JN/
    - assets/json/C02/ACT/
    - assets/json/C02/COL/
    - assets/json/C02/EPH/
    - assets/json/C02/GAL/
    - assets/json/C02/HEB/
    - assets/json/C02/JAS/
    - assets/json/C02/JHN/
    - assets/json/C02/JUD/
    - assets/json/C02/LUK/
    - assets/json/C02/MAT/
    - assets/json/C02/MRK/
    - assets/json/C02/PHM/
    - assets/json/C02/PHP/
    - assets/json/C02/REV/
    - assets/json/C02/ROM/
    - assets/json/C02/TIT/
    - assets/json/C02/index/
    - assets/json/C03/1CH/
    - assets/json/C03/1CO/
    - assets/json/C03/1JN/
    - assets/json/C03/1KI/
    - assets/json/C03/1PE/
    - assets/json/C03/1SA/
    - assets/json/C03/1TH/
    - assets/json/C03/1TI/
    - assets/json/C03/2CH/
    - assets/json/C03/2CO/
    - assets/json/C03/2JN/
    - assets/json/C03/2KI/
    - assets/json/C03/2PE/
    - assets/json/C03/2SA/
    - assets/json/C03/2TH/
    - assets/json/C03/2TI/
    - assets/json/C03/3JN/
    - assets/json/C03/ACT/
    - assets/json/C03/AMO/
    - assets/json/C03/COL/
    - assets/json/C03/DAN/
    - assets/json/C03/DEU/
    - assets/json/C03/ECC/
    - assets/json/C03/EPH/
    - assets/json/C03/EST/
    - assets/json/C03/EXO/
    - assets/json/C03/EZK/
    - assets/json/C03/EZR/
    - assets/json/C03/GAL/
    - assets/json/C03/GEN/
    - assets/json/C03/HAB/
    - assets/json/C03/HAG/
    - assets/json/C03/HEB/
    - assets/json/C03/HOS/
    - assets/json/C03/ISA/
    - assets/json/C03/JAS/
    - assets/json/C03/JDG/
    - assets/json/C03/JER/
    - assets/json/C03/JHN/
    - assets/json/C03/JOB/
    - assets/json/C03/JOL/
    - assets/json/C03/JON/
    - assets/json/C03/JOS/
    - assets/json/C03/JUD/
    - assets/json/C03/LAM/
    - assets/json/C03/LEV/
    - assets/json/C03/LUK/
    - assets/json/C03/MAL/
    - assets/json/C03/MAT/
    - assets/json/C03/MIC/
    - assets/json/C03/MRK/
    - assets/json/C03/NAM/
    - assets/json/C03/NEH/
    - assets/json/C03/NUM/
    - assets/json/C03/OBA/
    - assets/json/C03/PHM/
    - assets/json/C03/PHP/
    - assets/json/C03/PRO/
    - assets/json/C03/PSA/
    - assets/json/C03/REV/
    - assets/json/C03/ROM/
    - assets/json/C03/RUT/
    - assets/json/C03/SNG/
    - assets/json/C03/TIT/
    - assets/json/C03/ZEC/
    - assets/json/C03/ZEP/
    - assets/json/C03/index/
    - assets/json/C04/1CH/
    - assets/json/C04/1CO/
    - assets/json/C04/1JN/
    - assets/json/C04/1KI/
    - assets/json/C04/1PE/
    - assets/json/C04/1SA/
    - assets/json/C04/1TH/
    - assets/json/C04/1TI/
    - assets/json/C04/2CH/
    - assets/json/C04/2CO/
    - assets/json/C04/2JN/
    - assets/json/C04/2KI/
    - assets/json/C04/2PE/
    - assets/json/C04/2SA/
    - assets/json/C04/2TH/
    - assets/json/C04/2TI/
    - assets/json/C04/3JN/
    - assets/json/C04/ACT/
    - assets/json/C04/AMO/
    - assets/json/C04/COL/
    - assets/json/C04/DAN/
    - assets/json/C04/DEU/
    - assets/json/C04/ECC/
    - assets/json/C04/EPH/
    - assets/json/C04/EST/
    - assets/json/C04/EXO/
    - assets/json/C04/EZK/
    - assets/json/C04/EZR/
    - assets/json/C04/GAL/
    - assets/json/C04/GEN/
    - assets/json/C04/HAB/
    - assets/json/C04/HAG/
    - assets/json/C04/HEB/
    - assets/json/C04/HOS/
    - assets/json/C04/ISA/
    - assets/json/C04/JAS/
    - assets/json/C04/JDG/
    - assets/json/C04/JER/
    - assets/json/C04/JHN/
    - assets/json/C04/JOB/
    - assets/json/C04/JOL/
    - assets/json/C04/JON/
    - assets/json/C04/JOS/
    - assets/json/C04/JUD/
    - assets/json/C04/LAM/
    - assets/json/C04/LEV/
    - assets/json/C04/LUK/
    - assets/json/C04/MAL/
    - assets/json/C04/MAT/
    - assets/json/C04/MIC/
    - assets/json/C04/MRK/
    - assets/json/C04/NAM/
    - assets/json/C04/NEH/
    - assets/json/C04/NUM/
    - assets/json/C04/OBA/
    - assets/json/C04/PHM/
    - assets/json/C04/PHP/
    - assets/json/C04/PRO/
    - assets/json/C04/PSA/
    - assets/json/C04/REV/
    - assets/json/C04/ROM/
    - assets/json/C04/RUT/
    - assets/json/C04/SNG/
    - assets/json/C04/TIT/
    - assets/json/C04/ZEC/
    - assets/json/C04/ZEP/
    - assets/json/C04/index/
    - assets/json/C05/1CO/
    - assets/json/C05/1JN/
    - assets/json/C05/1PE/
    - assets/json/C05/1TH/
    - assets/json/C05/1TI/
    - assets/json/C05/2CO/
    - assets/json/C05/2JN/
    - assets/json/C05/2PE/
    - assets/json/C05/2TH/
    - assets/json/C05/2TI/
    - assets/json/C05/3JN/
    - assets/json/C05/ACT/
    - assets/json/C05/COL/
    - assets/json/C05/EPH/
    - assets/json/C05/GAL/
    - assets/json/C05/HEB/
    - assets/json/C05/JAS/
    - assets/json/C05/JHN/
    - assets/json/C05/JUD/
    - assets/json/C05/LUK/
    - assets/json/C05/MAT/
    - assets/json/C05/MRK/
    - assets/json/C05/PHM/
    - assets/json/C05/PHP/
    - assets/json/C05/REV/
    - assets/json/C05/ROM/
    - assets/json/C05/TIT/
    - assets/json/C05/index/
    - assets/project/
    - assets/translations.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # some fonts temporarily commented out for size reduction Feb 2023
  fonts:
    - family: font1
      fonts:
        - asset: assets/project/data/fonts/font1-R.ttf
        - asset: assets/project/data/fonts/font1-B.ttf
          weight: 700
    - family: font2
      fonts:
        - asset: assets/project/data/fonts/font2-R.ttf
        - asset: assets/project/data/fonts/font2-B.ttf
          weight: 700
    - family: font3
      fonts:
        - asset: assets/project/data/fonts/font3-R.ttf
        - asset: assets/project/data/fonts/font3-B.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
# https://pub.dev/packages/msix
# flutter pub run msix:create
msix_config:
  display_name: Kàddug Yàlla+
  publisher_display_name: Foundational LLC
  identity_name: 24971LaMBS.KddugYllagi
  msix_version: 1.0.4.0
  publisher: CN=172AFE7A-55C9-42B2-9D60-BAD846698B5E
  logo_path: C:\Users\corey\myflutter\wolof_bible\windows\runner\resources\app_icon.ico
  store: true
