import 'text_utils.dart';

/// BibleAbbreviations helper
/// - Maintains canonical → variants
/// - Builds fast lookup map
/// - Normalizes input for robust matching
/// Source of truth: Paratext 3‑letter code → list of variants
class BibleAbbreviations {
  /// Canonical Paratext 3‑letter code → list of known variants
  static final Map<String, List<String>> _variants = {
    // Old Testament
    "GEN": [
      "Gen",
      "Gen.",
      "Gn",
      "Ge",
      "Genese",
      "Genesis",
      "GEN",
      "Njalbeen ga",
      "Nja",
    ],
    "EXO": [
      "Ex",
      "Exod",
      "Exo",
      "Ex.",
      "Exode",
      "Exodus",
      "EXO",
      "Mucc ga",
      "Muc",
    ],
    "LEV": [
      "Lev",
      "Le",
      "Lv",
      "Levitique",
      "Leviticus",
      "LEV",
      "Sarxalkat yi",
      "Sar",
    ],
    "NUM": [
      "Num",
      "Nu",
      "Nm",
      "Nb",
      "Nombres",
      "Numbers",
      "NUM",
      "Mandin ma",
      "Man",
    ],
    "DEU": [
      "Deut",
      "De",
      "Dt",
      "Deuteronome",
      "Deuteronomy",
      "DEU",
      "Baamtug yoon wi",
      "Baa",
    ],
    "JOS": ["Josh", "Jos", "Jsh", "Josue", "Joshua", "JOS", "Yosuwe", "Yos"],
    "JDG": [
      "Judg",
      "Jdg",
      "Jg",
      "Jdgs",
      "Juges",
      "Judges",
      "JDG",
      "Njiit ya",
      "Nji",
    ],
    "RUT": ["Ruth", "Rth", "Ru", "RUT", "Ruut", "Ruu"],
    "1SA": [
      "1 Sam.",
      "1 Sm",
      "1 Sa",
      "1 S",
      "I Sam.",
      "I Sa",
      "1Sam",
      "1Sa",
      "1S",
      "1st Samuel",
      "First Samuel",
      "1 Samuel",
      "1SA",
      "1.Samiyel",
    ],
    "2SA": [
      "2 Sam.",
      "2 Sm",
      "2 Sa",
      "2 S",
      "II Sam.",
      "II Sa",
      "2Sam",
      "2Sa",
      "2S",
      "2nd Samuel",
      "Second Samuel",
      "2 Samuel",
      "2SA",
      "2.Samiyel",
    ],
    "1KI": [
      "1 Kings",
      "1 Kgs",
      "1 Ki",
      "1Kgs",
      "1Kin",
      "1Ki",
      "I Kgs",
      "I Ki",
      "1st Kings",
      "First Kings",
      "1 Rois",
      "1KI",
      "1.Buur ya",
      "1Bu",
    ],
    "2KI": [
      "2 Kings",
      "2 Kgs",
      "2 Ki",
      "2Kgs",
      "2Kin",
      "2Ki",
      "II Kgs",
      "II Ki",
      "2nd Kings",
      "Second Kings",
      "2 Rois",
      "2KI",
      "2.Buur ya",
      "2Bu",
    ],
    "1CH": [
      "1 Chron.",
      "1 Chr.",
      "1 Ch.",
      "1Chron.",
      "1Chr.",
      "1Ch.",
      "I Chron.",
      "I Chr.",
      "I Ch.",
      "1st Chronicles",
      "First Chronicles",
      "1 Chroniques",
      "1 Chronicles",
      "1CH",
      "1.Jaar-jaar ya",
      "1Ja",
    ],
    "2CH": [
      "2 Chron.",
      "2 Chr.",
      "2 Ch.",
      "2Chron.",
      "2Chr.",
      "2Ch.",
      "II Chron.",
      "II Chr.",
      "II Ch.",
      "2nd Chronicles",
      "Second Chronicles",
      "2 Chroniques",
      "2 Chronicles",
      "2CH",
      "2.Jaar-jaar ya",
      "2Ja",
    ],
    "EZR": ["Ezra", "Ezr.", "Ez.", "Esdras", "EZR", "Esra", "Esr"],
    "NEH": ["Neh.", "Ne.", "Nehemie", "Nehemiah", "NEH", "Neyemi", "Ney"],
    "EST": ["Est.", "Esth.", "Es.", "Esther", "EST", "Esteer", "Est"],
    "JOB": ["Job", "Jb.", "JOB", "Ayooba", "Ayo"],
    "PSA": [
      "Ps.",
      "Psalm",
      "Pslm.",
      "Psa.",
      "Psm.",
      "Pss.",
      "Psaume",
      "Psaumes",
      "Psalms",
      "PSA",
      "Taalifi cant",
      "Taa",
    ],
    "PRO": [
      "Prov",
      "Pro.",
      "Prv.",
      "Pr.",
      "Proverbes",
      "Proverbs",
      "PRO",
      "Kaddu yu xelu",
      "Kxe",
    ],
    "ECC": [
      "Eccles.",
      "Eccle.",
      "Ecc.",
      "Ec.",
      "Qoh.",
      "Ecclesiaste",
      "Ecclesiastes",
      "ECC",
      "Kadduy waare",
      "Kwa",
    ],
    "SNG": [
      "Song",
      "Song of Songs",
      "SOS.",
      "So.",
      "Canticles",
      "Cant.",
      "Cantique",
      "Cantique des cantiques",
      "Song of Solomon",
      "SNG",
      "Ngen-gi-woy",
      "Nge",
    ],
    "ISA": ["Isa.", "Is.", "Esaie", "Isaiah", "ISA", "Esayi", "Esa"],
    "JER": [
      "Jer.",
      "Je.",
      "Jr.",
      "Jeremie",
      "Jeremiah",
      "JER",
      "Yeremi",
      "Yer",
    ],
    "LAM": [
      "Lam.",
      "La.",
      "Lamentations",
      "LAM",
      "Lamentation de Jérémie",
      "Jooytu",
      "Joo",
    ],
    "EZK": [
      "Ezek.",
      "Eze.",
      "Ezk.",
      "Ezechiel",
      "Ezekiel",
      "EZK",
      "Esekiyel",
      "Ese",
    ],
    "DAN": ["Dan.", "Da.", "Dn.", "Daniel", "DAN", "Dañeel", "Dan"],
    "HOS": ["Hos.", "Ho.", "Osee", "Hosea", "HOS", "Ose"],
    "JOL": ["Joel", "Jl.", "JOL", "Yowel", "Yow"],
    "AMO": ["Amos", "Am.", "AMO", "Amo"],
    "OBA": ["Obad.", "Ob.", "Abdias", "Obadiah", "OBA", "Abdiyas", "Abd"],
    "JON": ["Jonah", "Jnh.", "Jon.", "Jonas", "JON", "Yunus", "Yun"],
    "MIC": ["Mic.", "Mc.", "Michee", "Micah", "MIC", "Mise", "Mis"],
    "NAM": ["Nah.", "Na.", "Nahum", "NAM", "Nawum", "Naw"],
    "HAB": ["Hab.", "Hb.", "Habacuc", "Habakkuk", "HAB", "Abakug", "Aba"],
    "ZEP": [
      "Zeph.",
      "Zep.",
      "Zp.",
      "Sophonie",
      "Zephaniah",
      "ZEP",
      "Sofoni",
      "Sof",
    ],
    "HAG": ["Hag.", "Hg.", "Aggee", "Haggai", "HAG", "Ase"],
    "ZEC": [
      "Zech.",
      "Zec.",
      "Zc.",
      "Zacharie",
      "Zechariah",
      "ZEC",
      "Sakkaryaa",
      "Sak",
    ],
    "MAL": ["Mal.", "Ml.", "Malachie", "Malachi", "MAL", "Malasi", "Mal"],

    // New Testament
    "MAT": ["Matt.", "Mt.", "Matthieu", "Matthew", "MAT", "Mace", "Mac"],
    "MRK": ["Mark", "Mrk", "Mar", "Mk", "Mr", "Marc", "MRK"],
    "LUK": ["Luke", "Luk", "Lk", "Luc", "LUK", "Luug", "Luu"],
    "JHN": ["John", "Joh", "Jhn", "Jn", "Jean", "JHN", "Yowaan", "Yow"],
    "ACT": ["Acts", "Act", "Ac", "Actes", "ACT", "Jef ya", "Jef"],
    "ROM": ["Rom.", "Ro.", "Rm.", "Romains", "Romans", "ROM", "Room", "Roo"],
    "1CO": [
      "1 Cor.",
      "1 Co.",
      "I Cor.",
      "I Co.",
      "1Cor.",
      "1Co.",
      "1st Corinthians",
      "First Corinthians",
      "1 Corinthiens",
      "1 Corinthians",
      "1CO",
      "1.Korent",
      "1Ko",
    ],
    "2CO": [
      "2 Cor.",
      "2 Co.",
      "II Cor.",
      "II Co.",
      "2Cor.",
      "2Co.",
      "2nd Corinthians",
      "Second Corinthians",
      "2 Corinthiens",
      "2 Corinthians",
      "2CO",
      "2.Korent",
      "2Ko",
    ],
    "GAL": ["Gal.", "Ga.", "Galates", "Galatians", "GAL", "Galasi"],
    "EPH": ["Eph.", "Ephes.", "Ephesiens", "Ephesians", "EPH", "Efes", "Efe"],
    "PHP": [
      "Phil.",
      "Php.",
      "Pp.",
      "Philippiens",
      "Philippians",
      "PHP",
      "Filib",
      "Fil",
    ],
    "COL": ["Col.", "Co.", "Colossiens", "Colossians", "COL", "Kolos", "Kol"],
    "1TH": [
      "1 Thess.",
      "1 Thes.",
      "1 Th.",
      "I Thess.",
      "I Thes.",
      "I Th.",
      "1Thess.",
      "1Th.",
      "1st Thessalonians",
      "First Thessalonians",
      "1 Thessaloniciens",
      "1 Thessalonians",
      "1TH",
      "1.Tesalonig",
      "1Th",
    ],
    "2TH": [
      "2 Thess.",
      "2 Thes.",
      "2 Th.",
      "II Thess.",
      "II Thes.",
      "II Th.",
      "2Thess.",
      "2Th.",
      "2nd Thessalonians",
      "Second Thessalonians",
      "2 Thessaloniciens",
      "2 Thessalonians",
      "2TH",
      "2.Tesalonig",
      "2Th",
    ],
    "1TI": [
      "1 Tim.",
      "1 Ti.",
      "I Tim.",
      "I Ti.",
      "1Tim.",
      "1Ti.",
      "1st Timothy",
      "First Timothy",
      "1 Timothee",
      "1 Timothy",
      "1TI",
      "1.Timote",
      "1Ti",
    ],
    "2TI": [
      "2 Tim.",
      "2 Ti.",
      "II Tim.",
      "II Ti.",
      "2Tim.",
      "2Ti.",
      "2nd Timothy",
      "Second Timothy",
      "2 Timothee",
      "2 Timothy",
      "2TI",
      "2.Timote",
      "2Ti",
    ],
    "TIT": ["Titus", "Tit", "Ti", "Tite", "TIT"],
    "PHM": ["Philem.", "Phm.", "Pm.", "Philemon", "PHM", "Filemon", "Fil"],
    "HEB": ["Heb.", "Hebreux", "Hebrews", "HEB", "Yawut ya", "Yaw"],
    "JAS": ["James", "Jas", "Jm", "Jacques", "JAS", "Yanqooba", "Yan"],
    "1PE": [
      "1 Pet.",
      "1 Pe.",
      "1 Pt.",
      "1 P.",
      "I Pet.",
      "I Pt.",
      "I Pe.",
      "1Pet.",
      "1Pe.",
      "1Pt.",
      "1P.",
      "1st Peter",
      "First Peter",
      "1 Pierre",
      "1 Peter",
      "1PE",
      "1.Piyeer",
      "1Pe",
    ],
    "2PE": [
      "2 Pet.",
      "2 Pe.",
      "2 Pt.",
      "2 P.",
      "II Pet.",
      "II Pt.",
      "II Pe.",
      "2Pet.",
      "2Pe.",
      "2Pt.",
      "2P.",
      "2nd Peter",
      "Second Peter",
      "2 Pierre",
      "2 Peter",
      "2PE",
      "2.Piyeer",
      "2Pe",
    ],
    "1JN": [
      "1 John",
      "1 Jhn.",
      "1 Jn.",
      "1 J.",
      "1Joh.",
      "1Jn.",
      "1Jo.",
      "1J.",
      "I John",
      "I Jhn.",
      "I Joh.",
      "I Jn.",
      "I Jo.",
      "1st John",
      "First John",
      "1 Jean",
      "1JN",
      "1.Yowaan",
      "1Yo",
    ],
    "2JN": [
      "2 John",
      "2 Jhn.",
      "2 Jn.",
      "2 J.",
      "2Joh.",
      "2Jn.",
      "2Jo.",
      "2J.",
      "II John",
      "II Jhn.",
      "II Joh.",
      "II Jn.",
      "II Jo.",
      "2nd John",
      "Second John",
      "2 Jean",
      "2JN",
      "2.Yowaan",
      "2Yo",
    ],
    "3JN": [
      "3 John",
      "3 Jhn.",
      "3 Jn.",
      "3 J.",
      "3Joh.",
      "3Jn.",
      "3Jo.",
      "3J.",
      "III John",
      "III Jhn.",
      "III Joh.",
      "III Jn.",
      "III Jo.",
      "3rd John",
      "Third John",
      "3 Jean",
      "3JN",
      "3.Yowaan",
      "3Yo",
    ],
    "JUD": ["Jude", "Jud.", "Jd.", "JUD", "Yudd", "Yud"],
    "REV": [
      "Rev",
      "Re",
      "The Revelation",
      "Apocalypse",
      "Revelation",
      "REV",
      "Peenu ma",
      "Pee",
    ],
  };

  static Map<String, List<String>> get abbreviations {
    return _variants;
  }

  /// Flat lookup map: variant → canonical
  static final Map<String, String> _lookup = _buildLookup();

  /// Normalize input: lowercase, strip punctuation/whitespace
  static String _normalize(String input) {
    return removeDiacritics(input).toLowerCase().replaceAll(
      RegExp(r'[^a-z0-9]'),
      '',
    ); // keep only alphanumerics
  }

  /// Build lookup map from variants
  static Map<String, String> _buildLookup() {
    final map = <String, String>{};
    for (final entry in _variants.entries) {
      for (final variant in entry.value) {
        map[_normalize(variant)] = entry.key;
      }
    }
    return map;
  }

  /// Public lookup method
  static String? lookup(String input) {
    return _lookup[_normalize(input)];
  }
}
