name: sfm_parser
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  xml: ^6.6.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
